### PR TITLE
Add Support for targeting multiple frameworks using `dotnet test`

### PR DESCRIPTION
**Pull request by mcblair**
This is a solution to #24, #27

### CODE REVIEW

**Comment by mcblair** [comment]
### Goals for this PR

- [ ] use `$(TargetFramework)` instead of timestamp

- [ ] Fix existing tests

- [ ] Add new tests

**Comment by SidShaytay** [comment]
+1 for `$(TargetFramework)` instead of timestamp.

**Comment by mcblair** [comment]
Currently investigating the best approach to getting ahold of the `$(TargetFramework)`.

https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0005-Test-Platform-SDK.md

Any input would be appreciated.

**Comment by codito** [comment]
@mcblair there is a `TestRunStart` event logger may subscribe to. We may be able to get the TargetFramework in this way:
- Subscribe to `TestLoggerEvents.TestRunStart`
- Get the `TestRunStartEventArgs.TestRunCriteria.TestRunSettings` in handler
- Parse the runsettings xml obtained above to get the `TargetFrameworkVersion` ([docs on runsettings structure](https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md#sample)

I am not sure if the `TestRunStart` event is exposed in ObjectModel 15.0 version nuget package, we may need to refer a later version.

Code references:
- https://github.com/Microsoft/vstest/blob/8746f3faa223dcccad78120e39a636b5b9206bbc/src/Microsoft.TestPlatform.ObjectModel/Logger/TestLoggerEvents.cs#L35
- https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Client/Events/TestRunStartEventArgs.cs
- https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Client/TestRunCriteria.cs

**Comment by codito** [comment]
@smadala @Faizan2304 please add if there's a better way to find runsettings/TargetFramework

**Comment by mcblair** [comment]
That's very helpful, will have something going soon.

**Comment by SidShaytay** [comment]
~~@mcblair @codito this is very similar to the one I reported to vstest at https://github.com/Microsoft/vstest/issues/1603 ... I think there is room for shared learning.~~

edit: Noticed @codito already referenced it above

**Comment by FrankyBoy** [comment]
I would argue it makes much more sense to allow for patterns in the filename that can be replaced instead of setting a property.

**Comment by codito** [comment]
@FrankyBoy do you mean something like below?

```sh
> dotnet test --test-adapter-path:. --logger:"nunit;LogFilePath=test-result.{testframework}.xml"
```

It will produce `test-result.net46.xml` and `test-result.netcoreapp20.xml`.

**Comment by codito** [comment]
Fixed with https://github.com/spekt/nunit.testlogger/commit/01d71099eae680deb074daed098b1201eb0c6629

**Comment by FrankyBoy** [comment]
Cool stuff 👍 

Now I just need to remember which of our infinite projects I had this issue with :D

**Pull request closed without merging**
