### PR TITLE
Added TeamCity.TestLogger

### PR DESCRIPTION
**Pull request by kevnord**
Greetings!
Thank you for creating the LoggerExtensions repo. Building a logger is extremely challenging so it was very helpful to have an example to look at. I've created a logger that outputs what TeamCity needs to report errors. Feel free to pull it into your master.

### CODE REVIEW

**Comment by codito** [comment]
@kevnord thanks for the pull request! There seems to be another (official?) teamcity test logger implementation here (https://github.com/JetBrains/TeamCity.VSTest.TestAdapter). Are these two implementations different in terms of functionality?

I'm wondering if jetbrains repo is the right home for this patch.

**Comment by kevnord** [comment]
@codito The official TeamCity test logger works great when outside of a docker build of a Dockerfile on a TeamCity agent. The PR code works within a docker build because it uses another way (console.writeline) to communicate with the TeamCity host. 

The issue and fix is described in....
https://devblog.bango.com/2017/10/13/build-in-docker-test-with-net-core-report-to-teamcity/

**Comment by codito** [comment]
@kevnord thanks, the context helps a lot. This scenario does make sense to me.

@NikolayPianikov @dtretyakov do you think this scenario is within scope of the official teamcity logger? May be adding a parameter to the official logger e.g. `--logger "teamcity;output=console"` (to write console messages) can help. This will keep related concepts together in single logger and it could evolve well if there are future changes in teamcity apis/service messages.

/cc @smadala

**Comment by NikolayPianikov** [comment]
@kevnord @codito [TeamCity logger](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter) uses [TeamCity service messages](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity) to pass data to TeamCity agent [via stdOut](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/blob/a6e4606094b7f5ac956f559440260d5c64f9c249/TeamCity.VSTest.TestLogger/ServiceLocator.cs#L10)

**Comment by kevnord** [comment]
@NikolayPianikov If i'm running dotnet test on a machine w/o TeamCity agent, do I need to pass in an enviro variable to instruct the writer to include the ##teamcity... 
I'm searching through code now.

**Comment by NikolayPianikov** [comment]
@kevnord yes, feel free to report bugs and to make PRs

**Comment by kevnord** [comment]
I figured it out with the help of a co-worker...

I had to add the following to my dockerfile above the call to dotnet test
ENV TEAMCITY_PROJECT_NAME=VideoService

Based on ...
https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/blob/d7efa83c652cd0d7169e4381b471dce54c4bdfec/TeamCity.VSTest.TestLogger/TeamCity.VSTest.TestAdapter.props

I'll likely make the environment variable based on an argument that's passed into the build command

It's nifty that the TeamCity specific formatting is only added when you're on machine running the TeamCity agent (based on these environment vars) but man that wasn't obvious.

I'll add a PR to update the Readme to save some others the pain of figuring this all out.

Appreciate ALL of the help that you guys have provided!

**Comment by NikolayPianikov** [comment]
@kevnord thank you, it would be great

**Pull request closed without merging**
