### PR TITLE
 Respect ResultsDirectory #46 

### PR DESCRIPTION
**Pull request by ashishdawale20**
Changes for issue #46

### CODE REVIEW

**Comment by codito** [comment]
@ashishdawale20 thanks for the contribution. It seems your fix branch is couple of commits behind `spekt:master`, can you please sync to latest?

Please consider adding a test for this change. It should be simple (here's an example commit with a test: https://github.com/spekt/nunit.testlogger/commit/01d71099eae680deb074daed098b1201eb0c6629).

**Comment by ashishdawale20** [comment]
@codito 
I am not able to build AcceptanceTest project. It is giving below error.
Do i need to create a nuget package 2.1.0-dev package. Can you please here?

image

**Comment by codito** [comment]
Ah, I think the error is because `dotnet pack` has not been run.

Can you try running `.\build.ps1` from a powershell command prompt? It will first create the package and then run the tests.

Edit: this is the build script - [build.ps1](https://github.com/spekt/nunit.testlogger/blob/master/build.ps1).

**Comment by ashishdawale20** [comment]
Hi @codito,
Added acceptance test, please have a look.

**Review by codito — APPROVED** [review]

**Comment by codito** [comment]
Looks good! Thanks @ashishdawale20 for the contribution.

**Pull request merged**
